### PR TITLE
Doc 9675 updates

### PR DESCRIPTION
**Pull request by dlutzCoveo**

### CODE REVIEW

**Comment by jpmarceau** [comment]
Do you have something in the works to update the writeup?
https://levelup.coveo.com/learn/courses/headless-tutorial/lessons/lesson-1-understanding-the-core-concepts#_engine

**Comment by dlutzCoveo** [comment]
I've updated dependancies  (and rebuilt the package-lock.json), the engine imports, and the export on the engine. I'll need to apply these to the main and finished tutorial; after reviewing this I can apply the same edits to that branch.

**Comment by dlutzCoveo** [comment]
> Do you have something in the works to update the writeup?
> https://levelup.coveo.com/learn/courses/headless-tutorial/lessons/lesson-1-understanding-the-core-concepts#_engine

Yes, sorry I didn't add that here when creating the PR! 
https://levelup.coveo.com/authoring/branches/C101-819-update-headless-tutorial/learn/courses/headless-tutorial/lessons/lesson-1-understanding-the-core-concepts

**Review by kaitlynkatz — APPROVED** [review]
Looks good to me, we should merge in sync with the tutorial changes though.

(Also note, so I don't have to say this every time: in general I'm not running any of the code I review for you, I'm just doing a thorough read-through. If you ever want me to run something just let me know, and make sure you always run stuff after applying my suggestions to make sure I didn't make a mistake 😄 )

**Review by jpmarceau — APPROVED** [review]
Looks good and works fine 👍 

In theory, the best thing to do with the finished-tutorial branch would be to sync it with main, but it could be good to test it locally before pushing that update to make sure we don't break something ;p

**Pull request merged**
