### PR TITLE
bump version and update action dispatching

### PR DESCRIPTION
**Pull request by jpmarceau**
Hmm actually don't review this yet, there seems to be a bug when updating to version 16.2, and I haven't quite figured it out.
https://codesandbox.io/s/keen-villani-nlfwr
I think I'l reach out to the ui-kit team...

### CODE REVIEW

**Comment by jpmarceau** [comment]
Update: I asked Benjamin about the warning we're getting on version 16.2, and he has created a Jira to fix it.
I think we have two options: 
1- not update this sample or the tutorial until Benjamin has fixed the warning. This has the advantage of keeping the console clean for people going through the tutorial.
2- update now anyways, since the the warning doesn't really prevent things from working. This has the advantage of showing the proper way of dispatching actions in the tutorial

Personally I tend slightly more towards 2, but I'd be curious to know what you think.

**Comment by kaitlynkatz** [comment]
> Update: I asked Benjamin about the warning we're getting on version 16.2, and he has created a Jira to fix it.
> I think we have two options:
> 1- not update this sample or the tutorial until Benjamin has fixed the warning. This has the advantage of keeping the console clean for people going through the tutorial.
> 2- update now anyways, since the the warning doesn't really prevent things from working. This has the advantage of showing the proper way of dispatching actions in the tutorial
> 
> Personally I tend slightly more towards 2, but I'd be curious to know what you think.

I know 0.16.2 is the first version where the old way of doing actions is _deprecated_, but I'm pretty sure Sami had created the new way before that. You could check if you can use the new action dispatch way with 0.13.0, because if you can that's the most optimal solution, but it may be the case that not all the new loader functions had been created yet. Otherwise I don't really have an opinion, they're both meh solutions.

**Comment by jpmarceau** [comment]
> > Update: I asked Benjamin about the warning we're getting on version 16.2, and he has created a Jira to fix it.
> > I think we have two options:
> > 1- not update this sample or the tutorial until Benjamin has fixed the warning. This has the advantage of keeping the console clean for people going through the tutorial.
> > 2- update now anyways, since the the warning doesn't really prevent things from working. This has the advantage of showing the proper way of dispatching actions in the tutorial
> > Personally I tend slightly more towards 2, but I'd be curious to know what you think.
> 
> I know 0.16.2 is the first version where the old way of doing actions is _deprecated_, but I'm pretty sure Sami had created the new way before that. You could check if you can use the new action dispatch way with 0.13.0, because if you can that's the most optimal solution, but it may be the case that not all the new loader functions had been created yet. Otherwise I don't really have an opinion, they're both meh solutions.

Good suggestion. Sadly there's no version where the new action dispatching functionality works and we don't get the warning 😢

**Review by kaitlynkatz — APPROVED** [review]
Not sure if you'll end up merging this now or not, but if we go for that option this looks fine 👍🏻

**Pull request merged**
